(load "AgentKit:tasks")

(set APP (dict name:"q"
               path:"q"
            workers:1
            domains:""
        description:"App store."))

(set AGENT "https://alpha.agent.io")
(set CREDENTIALS "admin:master123")
