(set appname "accounts")

(set agentbox "http://alpha.agent.io")
(set credentials "admin:master")


(task "zip" is
      (SH "mkdir -p build/#{appname}.app")
      (SH "cp -r keys.nu build/#{appname}.app")
      (SH "cp #{appname} build/#{appname}.app/#{appname}")
      (SH "cd build; zip -r #{appname}.zip #{appname}.app"))

(task "pub" => "zip" is
      (set command (+ "curl -s " agentbox "/control/api/"
                      appname
                      " -T build/#{appname}.zip"
                      " -X POST"
                      " -u " credentials))
      (puts command)
      (set version (NSString stringWithShellCommand:command))
      (puts "app version: #{version}")
      (set command (+ "curl -s " agentbox "/control/api/"
                      appname
                      "/deploy/"
                      version
                      " -X POST"
                      " -u " credentials))
      (set result (NSString stringWithShellCommand:command))
      (puts "deployment result: #{result}"))

(task "default" => "zip")

