(load "AgentKit:tasks")

(set APP (dict name:"accounts"
               path:"accounts"
            workers:1
            domains:""
        description:"Agent account manager."))

(set AGENT "https://alpha.agent.io")
(set CREDENTIALS "admin:master123")
