(load "AgentKit:tasks")

(set APP (dict name:"mail"
               path:"mail"
             system:1
            workers:1
            domains:""
        description:"Agent mail account manager."))

(set AGENT "https://alpha.agent.io")
(set CREDENTIALS "admin:master123")
