(load "AgentKit:tasks")

(set APP (dict name:"files"
               path:"files"
            workers:1
            domains:""
        description:"Agent file storage."))

(set AGENT "https://alpha.agent.io")
(set CREDENTIALS "admin:master123")
