(load "AgentKit:tasks")

(set APP (dict name:"home"
               path:"home"
            workers:1
            domains:""
        description:"Agent home."))

(set AGENT "https://alpha.agent.io")
(set CREDENTIALS "admin:master123")
