(load "AgentKit:tasks")

(set APP (dict name:"grid"
               path:"grid"
            workers:1
            domains:""
        description:"Agent grid storage."))

(set AGENT "https://alpha.agent.io")
(set CREDENTIALS "admin:master123")
