(load "AgentKit:tasks")

(set APP (dict name:"signin"
               path:"signin"
            workers:1
            domains:""
        description:"Agent signin service."))

(set AGENT "http://alpha.agent.io")
(set CREDENTIALS "admin:master123")
