(load "AgentKit:tasks")

(set APP (dict name:"abitalk"
               path:"abitalk"
            workers:1
            domains:""
        description:"Abitalk API"))

(set AGENT "https://alpha.agent.io")
(set CREDENTIALS "admin:master123")
