(load "AgentKit:tasks")

(set APP (dict name:"apps"
               path:"apps"
            workers:1
            domains:""
        description:"Agent app manager."))

(set AGENT "https://alpha.agent.io")
(set CREDENTIALS "admin:master123")
