(load "AgentJSON")

(set appname "chief")

(set agentbox "http://alpha.agent.io")
(set credentials "admin:master123")

(task "zip" is
      (SH "mkdir -p build/#{appname}.app")
      (SH "cp #{appname} build/#{appname}.app")
      (SH "cd build; zip -r #{appname}.zip #{appname}.app"))

(task "pub" => "zip" is
      ;; upload a new app version
      (set command (+ "curl -s " agentbox "/control/api/"
                      appname
                      " -T build/#{appname}.zip"
                      " -X POST"
                      " -u " credentials))
      (puts command)
      (set version (NSString stringWithShellCommand:command))
      (puts "app version: #{version}")
      (set command (+ "curl -s " agentbox "/control/api/"
                      appname
                      "/deploy/"
                      version
                      " -X POST"
                      " -u " credentials))
      (set result (NSString stringWithShellCommand:command))
      (puts "deployment result: #{result}"))


(task "list" is
      (set command (+ "curl -s " agentbox "/control/api/apps"
                      " -u " credentials))
      (puts command)
      (set results (NSData dataWithShellCommand:command))
      (global APPS ((results propertyListValue) apps:))
      (APPS each:
            (do (APP)
                (puts (APP name:))
                (puts (APP _id:))))
      "OK")


(task "delete" => "list" is
      (set app (APPS find:(do (app) (eq (app name:) "chief"))))
      (if app
          (then (set command (+ "curl -s " agentbox "/control/api/apps/" (app _id:)
                                " -X DELETE"
                                " -u " credentials))
                (puts command)
                (set results (NSString stringWithShellCommand:command))
                (puts "apps: #{(results description)}"))
          (else "App not found")))

(task "create" is
      (set command (+ "curl -s "
                      " -d \"name=chief&path=chief&workers=1&domains=&description=\""
                      " -X POST"
                      " " agentbox "/control/api/apps"
                      " -u " credentials))
      (puts command)
      (set results (NSString stringWithShellCommand:command))
      (puts "apps: #{(results description)}"))

(task "restart" is
      (set command (+ "curl -s "
                      " -X POST"
                      " " agentbox "/control/api/nginx/restart"
                      " -u " credentials))
      (puts command)
      (set results (NSString stringWithShellCommand:command))
      (puts "apps: #{(results description)}"))

(task "account" is
      (set command (+ "curl -s "
                      " -X GET"
                      " " agentbox "/control/api/account"
                      " -u " credentials))
      (puts command)
      (set results (NSString stringWithShellCommand:command))
      (puts "apps: #{(results description)}"))

(task "default" => "zip")

