(load "AgentKit:tasks")

(set APP (dict name:"collections"
               path:"collections"
            workers:1
            domains:""
        description:"Agent data editor."))

(set AGENT "https://alpha.agent.io")
(set CREDENTIALS "admin:master123")
